=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex1.dtd
<!ENTITY comentario "Es muy bonito">
<!ENTITY % marcas "marca CDATA #REQUIRED">

<!ELEMENT papeleria (tipo)>
<!ELEMENT tipo (papel?, escritura+)>
<!ELEMENT escritura (boligrafos*, lapices, rotuladores)>
<!ELEMENT papel (cuadernos | libros | cartulina)*>
<!ELEMENT cartulina EMPTY >
<!ELEMENT libros (#PCDATA)>
<!ELEMENT cuadernos (#PCDATA | pastadura)*>
<!ELEMENT pastadura EMPTY>
<!ELEMENT rotuladores EMPTY>
<!ELEMENT boligrafos ANY>
<!ELEMENT lapices (#PCDATA)>

<!ATTLIST boligrafos color (azul | rojo | verde | negro) #REQUIRED>
<!ATTLIST lapices %marcas;
					dureza CDATA #IMPLIED
					escriben_en IDREF #REQUIRED>
<!ATTLIST pastadura valor NMTOKEN #FIXED "Si"> 
<!ATTLIST cartulina tamaÃ±o ID #REQUIRED>
<!ATTLIST rotuladores %marcas;
					sirven_para IDREFS #REQUIRED>

=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles SYSTEM "Ex1.dtd">
<papeleria>
	<tipo>
		<papel>
			<cartulina tama単o= "A5"/>
			<cuadernos><pastadura valor = "Si"/>Cuaderno tama単o A2</cuadernos>
			<libros>Los pilares de la Tierra. &comentario; </libros>
			<cartulina tama単o= "A2"/>
			<cartulina tama単o= "A3"/>
		</papel>
		<escritura>
			<boligrafos color="azul">Escribe muy bien</boligrafos>
			<boligrafos color="rojo"></boligrafos>
			<lapices marca="bic" escriben_en="A2">Lo uso en clase de dibujo</lapices>
			<rotuladores marca= "crayola" sirven_para="A2 A5"/>
		</escritura>
		<escritura>
			<boligrafos color="verde"> &comentario; </boligrafos>
			<lapices marca="pilot" escriben_en="A5">Lo uso en clase de dibujo</lapices>
			<rotuladores marca= "carioca" sirven_para="A2 A3"/>
		</escritura>
	</tipo>
</papeleria>
