=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex2.dtd
<!ENTITY comentario "Esta marca hace relojes de muy buena calidad y comodos">
<!ENTITY % caracteristicas "fecha_creacion CDATA #REQUIRED">

<!ELEMENT tienda (articulos)>
<!ELEMENT articulos (relojes*)>
<!ELEMENT relojes (marca+)>
<!ELEMENT marca (#PCDATA | reloj)*>
<!ELEMENT reloj (precio | piezas | descuento?)*>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT piezas EMPTY>
<!ELEMENT descuento (#PCDATA | fecha)*>
<!ELEMENT fecha (#PCDATA)>

<!ATTLIST marca	nombre ID #REQUIRED>

<!ATTLIST piezas %caracteristicas;
					fabricante IDREFS #REQUIRED>
<!ATTLIST reloj %caracteristicas;
				fabricante IDREF #REQUIRED
				color (negro | blanco | plata | oro) #IMPLIED
				pila_incluida NMTOKEN #FIXED "Si">

=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles SYSTEM "Ex2.dtd">
<tienda>
	<articulos>
		<relojes>
			<marca nombre="rolex"> &comentario;
				<reloj fecha_creacion="12-05-2018" fabricante="rolex" color="blanco" pila_incluida="Si">
					<precio>32 Euros</precio>
					<piezas fecha_creacion="23-12-2013" fabricante="rolex"/>
					<descuento><fecha>de Enero a Febrero</fecha> 10% de descuento</descuento>
				</reloj>
				<reloj fecha_creacion="04-07-2018" fabricante="rolex" color="plata">
					<precio>32 Euros</precio>
					<piezas fecha_creacion="23-12-2013" fabricante="rolex"/>
				</reloj>
			</marca>
			<marca nombre="ratio">
				<reloj fecha_creacion="12-05-2018" fabricante="ratio" color="negro" pila_incluida="Si">
					<piezas fecha_creacion="23-12-2013" fabricante="ratio"/>
					<precio>32 Euros</precio>
					<descuento><fecha>de Enero a Febrero</fecha> 25% de descuento</descuento>
				</reloj>
				<reloj fecha_creacion="20-02-2015" fabricante="ratio">
					<precio>32 Euros</precio>
					<piezas fecha_creacion="23-12-2013" fabricante="rolex ratio"/>
				</reloj>
			</marca>
		</relojes>
	</articulos>
</tienda>
