=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex3.dtd
<!ENTITY % nombre "nombre CDATA #REQUIRED">
<!ENTITY comentario "Esta habilidad es muy potente">

<!ELEMENT riot (leagueoflegends)>
<!ELEMENT leagueoflegends (personaje)*>
<!ELEMENT personaje (clase, raza, sexo?, habilidades+)>
<!ELEMENT habilidades (#PCDATA | magicas | fisicas)*>
<!ELEMENT magicas EMPTY>
<!ELEMENT fisicas EMPTY>
<!ELEMENT clase EMPTY>
<!ELEMENT raza (#PCDATA)>
<!ELEMENT sexo EMPTY>


<!ATTLIST personaje %nombre;
					tipo ID #REQUIRED
					invocacion NMTOKEN #FIXED "Si" >
<!ATTLIST clase nombre IDREFS #REQUIRED>
<!ATTLIST sexo valor (masculino | femenino | desconocido) #IMPLIED>
<!ATTLIST raza %nombre;>
<!ATTLIST fisicas tipo IDREF #REQUIRED>
<!ATTLIST magicas tipo IDREF #REQUIRED>

=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/Ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles SYSTEM "Ex3.dtd">
<riot>
	<leagueoflegends>
		<personaje nombre= "Xayah" tipo= "adc" invocacion="Si"> 
			<clase nombre= "adc"/>
			<raza nombre= "Vastaya"> Animales con apariencia de persona </raza>
			<sexo valor= "femenino"/>
			<habilidades><fisicas tipo="adc"/>Dagas afiladas</habilidades>
			<habilidades> Lluvia de plumas &comentario;
				<magicas tipo="mago"/>
			</habilidades>
		</personaje>
		<personaje nombre= "Rakan" tipo= "support" invocacion="Si">
			<clase nombre= "support mago"/>
			<raza nombre= "Vastaya"> Animales con apariencia de persona </raza>
			<sexo valor= "masculino"/>
			<habilidades> Sanacion
				<magicas tipo="support"/>
			</habilidades>
		</personaje>
		<personaje nombre= "Ahri" tipo= "mago">
			<clase nombre= "mago"/>
			<raza nombre= "Vastaya"> Animales con apariencia de persona </raza>
			<habilidades> Orbe de la perdici√≥n &comentario;
				<magicas tipo ="mago"/>
			</habilidades>
		</personaje>
	</leagueoflegends>
</riot>
