=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/ExamenMariaPerezEscalera.dtd
<!ENTITY % nombre "nombre CDATA #REQUIRED">
<!ENTITY comentario "todos los pesos estan cogidos en gramos:">
<!ELEMENT obrador (receta)*>
<!ELEMENT receta (dulces)>
<!ELEMENT dulces (tradicionales | vanguardia)>
<!ELEMENT tradicionales (nombreT, ingredientes, (temporalidad | festividad))>
<!ELEMENT vanguardia (nombreV, tecnicas, sabor+, peso?)>
<!ELEMENT nombreT EMPTY>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT temporalidad EMPTY>
<!ELEMENT festividad EMPTY>
<!ELEMENT nombreV EMPTY>
<!ELEMENT tecnicas (#PCDATA | utensilios)*>
<!ELEMENT sabor EMPTY>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT utensilios EMPTY>

<!ATTLIST temporalidad epoca (invierno | primavera | verano | otoÃ±o) #REQUIRED>
<!ATTLIST festividad fiesta (navidad | halloween | semana_santa) #IMPLIED>
<!ATTLIST nombreT %nombre;
					realizado_por IDREF #REQUIRED>
<!ATTLIST nombreV %nombre;>
<!ATTLIST utensilios nombre NMTOKENS #IMPLIED
						se_utilizan_en IDREFS #REQUIRED>
<!ATTLIST sabor tipo CDATA #REQUIRED
				dulce CDATA #FIXED "Si">
<!ATTLIST tecnicas %nombre;
					id ID #REQUIRED>
<!ATTLIST tradicionales trabajador ID #REQUIRED>

=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/DTD/ExamenMariaPerezEscalera.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles SYSTEM "ExamenMariaPerezEscalera.dtd">
<obrador>
	<receta>
		<dulces>
			<tradicionales trabajador="Maria">
				<nombreT nombre = "Huesos de santo" realizado_por="Maria"/>
				<ingredientes> Harina de almendra, yemas y az√∫car</ingredientes>
				<festividad fiesta="semana_santa"/>
			</tradicionales>
		</dulces>
	</receta>
	<receta>
		<dulces>
			<vanguardia>
				<nombreV nombre = "Cupula de chocolate con aire de avellana"/>
				<tecnicas nombre = "Atemperado" id="T1">
					<utensilios nombre= "Globos de plastico" se_utilizan_en="T1"/>
					<utensilios nombre= "Espatulas" se_utilizan_en="T1 T2"/>
				</tecnicas>
				<sabor tipo ="avellana" dulce="Si"/>
				<peso> &comentario; 220</peso>
			</vanguardia>
		</dulces>
	</receta>
	<receta>
		<dulces>
			<vanguardia>
				<nombreV nombre = "Gelatina de fruta de la pasion con palomitas de vainilla"/>
				<tecnicas nombre = "Gelificacion" id="T2">
					<utensilios nombre= "Nitrogeno liquido" se_utilizan_en="T2"/>
					<utensilios nombre= "Espatulas" se_utilizan_en="T1 T2"/>
				</tecnicas>
				<sabor tipo="vainilla" dulce="Si"/>
				<sabor tipo="fruta de la pasion"/>
			</vanguardia>
		</dulces>
	</receta>
</obrador>
