<?xml version="1.0" encoding="UTF-8"?>

<!-- Realiza un XML, y su correspondiente DTD, que permita almacenar información sobre 
tarjetas de placa base de manera que cumplas los siguientes requisitos: 
Se debe poder guardar información, para cada placa, de los componentes siguientes: microprocesador, memoria, 
modelo, fabricante. Debes guardar especial atención a la cardinalidad de cada elemento, para que sea la adecuada. 
	El microprocesador, la memoria y el modelo podrán almacenar texto.
El fabricante podrá ser "Asus" o "Intel". El valor del fabricante no puede ser un texto, tiene que ser un 
elemento vacío. Recuerda que una placa base no puede tener más de un fabricante, ni menos. Piensa en la cardinalidad. -->

<!DOCTYPE tarjetas [
	<!ELEMENT tarjetas (placasbase+)>
	<!ELEMENT placasbase (microprocesador, memoria+, modelo, fabricante)>
	<!ELEMENT microprocesador (#PCDATA)>
	<!ELEMENT memoria (#PCDATA)>
	<!ELEMENT modelo (#PCDATA)>
	<!ELEMENT fabricante (Asus | Intel)>
	<!ELEMENT Asus EMPTY>
	<!ELEMENT Intel EMPTY>
]>
<tarjetas>
	<placasbase>
		<microprocesador>Tipo de microprocesador</microprocesador>
		<memoria>Tipo de memoria 1</memoria>
		<memoria>Tipo de memoria 2</memoria>
		<modelo>Modelo ABC</modelo>
		<fabricante><Asus/></fabricante>
	</placasbase>
	<placasbase>
		<microprocesador>Tipo de microprocesador</microprocesador>
		<memoria>Tipo de memoria 1</memoria>
		<memoria>Tipo de memoria 2</memoria>
		<memoria>Tipo de memoria 3</memoria>
		<memoria>Tipo de memoria 4</memoria>
		<modelo>Modelo ABCD</modelo>
		<fabricante><Intel/></fabricante>
	</placasbase>
</tarjetas>