=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/Ejercicios_Ex.dtd
<!DOCTYPE arboles [
  <!ENTITY % caracteristicas "nombre CDATA #REQUIRED nombrecientifico CDATA #IMPLIED">
  
  <!ELEMENT arboles (arbol | arbusto)*>
  <!ELEMENT arbol (frutal | nofrutal)*>
  
  <!ELEMENT frutal (#PCDATA | fruta)*>
  <!ELEMENT fruta EMPTY>
  <!ELEMENT nofrutal EMPTY>
  <!ATTLIST fruta color CDATA #REQUIRED
  					hueso >
  <!ATTLIST nofrutal %caracteristicas;>
  
  <!ELEMENT arbusto EMPTY>
  <!ATTLIST arbusto nombre CDATA #REQUIRED >
]>

=== MariaPE10/EjerciciosLM/Ejercicios_LM/src/Examen/Ejercicios_Ex.xml
<?xml version="1.0" encoding="UTF-8"?> <!-- Frutas y Ã¡rboles de los que proceden -->
<!DOCTYPE arboles SYSTEM "Ejercicios_Ex.dtd">
<arboles>
	<arbol>
		<frutal identificador ="a1"> Es un arbol muy bonito. &flores;
			<fruta nombre="Manzana" hueso="Si" color="rojo" pertenece_a="a1"/>
			<fruta nombre="Pera" hueso="Si" pertenece_a="a1"/>
		</frutal>
		<frutal identificador ="a2"> Es un arbol robusto
			<fruta nombre="Naranjo" hueso="Si" color="naranja" pertenece_a="a2"/>
		</frutal>
	</arbol>
	<arbol>
		<arbusto nombre="Tomillo" nombrecientifico="Tomillus Alcacicus"/>
		<arbusto nombre="Zarza" nombrecientifico="Morus Dulce" familia_de="a3"/>
		<arbusto nombre="Romero" nombrecientifico="Romerus" familia_de="a1 a2"/>
	</arbol>
	<arbol>
		<frutal identificador ="a3"> Es un arbol con puas &flores;
			<fruta nombre="Limonero" hueso="Si" color="amarillo" pertenece_a="a3"/>
		</frutal>
		<nofrutal nombre="Pino" nombrecientifico="Pinus Pinchoso"/>
	</arbol>
</arboles>
